### ISSUE TITLE
NoClassDefFoundError (x60) on server shutdown

### ISSUE THREAD

**Issue by SlimeDog** [InsightsPlugin/BentoBoxAddon#2]
60 of these occur on server shutdown. The BentoBox team says "Report this to "Insights" Please. They seem to attempt to access the BentoBox API after bentobox has unloaded." (https://github.com/BentoBoxWorld/BentoBox/issues/1848#issuecomment-913858412)

```
[14:06:14 ERROR]: Could not pass event EntityRemoveFromWorldEvent to Insights v6.7.1
java.lang.NoClassDefFoundError: world/bentobox/bentobox/managers/IslandsManager
        at dev.frankheijden.insights.addons.bentobox.BentoBoxAddon.getRegion(BentoBoxAddon.java:51) ~[?:?]
        at dev.frankheijden.insights.api.addons.AddonManager.getRegion(AddonManager.java:150) ~[Insights-6.7.1.jar:?]
        at dev.frankheijden.insights.api.listeners.InsightsListener.handleModification(InsightsListener.java:59) ~[Insights-6.7.1.jar:?]
        at dev.frankheijden.insights.api.listeners.InsightsListener.handleModification(InsightsListener.java:72) ~[Insights-6.7.1.jar:?]
        at dev.frankheijden.insights.listeners.EntityListener.handleEntityRemoval(EntityListener.java:195) ~[Insights-6.7.1.jar:?]
        at dev.frankheijden.insights.listeners.EntityListener.handleEntityRemoveFromWorld(EntityListener.java:158) ~[Insights-6.7.1.jar:?]
        at dev.frankheijden.insights.listeners.PaperEntityListener.onEntityRemove(PaperEntityListener.java:21) ~[Insights-6.7.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor274.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-251]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.level.WorldServer$a.a(WorldServer.java:2453) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.level.WorldServer$a.a(WorldServer.java:2333) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.f(PersistentEntitySectionManager.java:221) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager$a.a(PersistentEntitySectionManager.java:599) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4123) ~[patched_1.17.1.jar:git-Paper-251]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.EntityNMSArmorStand.killEntityNMS(EntityNMSArmorStand.java:205) ~[HolographicDisplays-2.4.9-b180.jar:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.despawn(CraftTextLine.java:115) ~[HolographicDisplays-2.4.9-b180.jar:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.despawnEntities(CraftHologram.java:306) ~[HolographicDisplays-2.4.9-b180.jar:?]
        at com.gmail.filoghost.holographicdisplays.HolographicDisplays.onDisable(HolographicDisplays.java:178) ~[HolographicDisplays-2.4.9-b180.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.17.1.jar:git-Paper-251]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:469) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:1045) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:806) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1324) ~[patched_1.17.1.jar:git-Paper-251]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-251]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by FrankHeijden** [comment]
Yeah, so actually its an incompatibility with HolographicDisplays, and unfortunate ordering of the plugins on shutdown. I suspect the order of those three plugins together is BentoBox, HolographicDisplays and finally Insights. HolographicDisplays kills all entities on shutdown, and since Insights listens for that event it will ask BentoBox for its regions, but its unloaded. This PR aims to fix the problem: https://github.com/InsightsPlugin/Insights/pull/136. Builds will be available from GH actions, could you verify it solves the problem?

**Comment by SlimeDog** [comment]
Insights 6.7.2-b380 looks good on both Paper and Spigot (two tests each).

**Comment by FrankHeijden** [comment]
Nice! Merging & releasing tomorrow.
